async function main() {
	// you have to re
}

main().catch((error) => {
	console.error(error)
	process.exitCode = 1
})
